// Words on the guest menu page, Bulgarian first. {n}, {time} and friends
// are filled in by fill().

export const fill = (text, values) => text.replace(/\{(\w+)\}/g, (_, k) => (values[k] ?? ""));

export const strings = {
  bg: {
    title: "Меню",
    restaurant: "RAYA Garden",
    table: "Маса",
    tableN: "Маса №{n}",
    change: "смени",
    chooseTable: "На коя маса сте?",
    chooseTableLead: "Номерът е на табелката на масата.",
    justBrowsing: "Само разглеждам",
    add: "Добави",
    added: "Добавено",
    soldOut: "Изчерпано",
    byWeight: "По тегло · поръчва се при сервитьора",
    per100: "за 100 г",
    itemsOne: "1 артикул",
    itemsMany: "{n} артикула",
    review: "Преглед на поръчката",
    yourOrder: "Вашата поръчка",
    note: "Бележка",
    notePlaceholder: "по желание, напр. без лук",
    total: "Общо",
    payment: "Плащането е на място при персонала.",
    payOnline: "Плащате с карта в телефона — Apple Pay, Google Pay или карта. Поръчката отива при персонала, щом плащането мине.",
    payButton: "Плати {total}",
    toPayment: "Към плащането…",
    payNow: "Плати",
    paid: "Платена",
    refunded: "Сумата е върната",
    confirmingPayment: "Потвърждаваме плащането…",
    unpaidReturn: "Плащането не е завършено, затова поръчката не е изпратена. Можете да платите сега или да поръчате отново.",
    paymentUnavailable: "Плащането не може да започне в момента. Опитайте отново — поръчката няма да се дублира.",
    confirmTable: "Потвърждавам, че съм на маса №{n}",
    send: "Изпрати поръчката",
    sending: "Изпращане…",
    emptyCart: "Все още не сте добавили нищо.",
    closed: "Поръчките онлайн в момента не се приемат.",
    notYetToday: "Отваряме за поръчки днес в {time}.",
    notYetOn: "Отваряме за поръчки на {date} в {time}.",
    paused: "Приемането на поръчки е временно спряно. Моля, повикайте сервитьор.",
    browseStill: "Менюто можете да разгледате.",
    sent: "Поръчката е изпратена",
    sentLead: "Персоналът я вижда. Покажете кода, ако ви попитат.",
    code: "Код",
    status: {
      pending_payment: "Очаква плащане · още не е изпратена",
      expired: "Неплатена · не е изпратена",
      new: "Изпратена · очаква потвърждение",
      accepted: "Приета · приготвя се",
      served: "Сервирана",
      cancelled: "Отказана",
    },
    myOrders: "Моите поръчки",
    ordersShort: "Поръчки",
    orderMore: "Поръчай още",
    changedTitle: "Менюто се промени",
    changedLead: "Поръчката не е изпратена. Прегледайте промените и я изпратете отново.",
    removedLine: "{name} — вече не се предлага, премахнато",
    soldOutLine: "{name} — изчерпано, премахнато",
    priceLine: "{name}: {old} → {now}",
    tableInvalid: "Маса №{n} не приема поръчки. Моля, изберете масата си отново.",
    rateLimited: "Твърде много поръчки за кратко време. Опитайте след малко или повикайте сервитьор.",
    network: "Няма връзка. Проверете интернета и опитайте отново — поръчката няма да се изпрати два пъти.",
    error: "Нещо се обърка. Опитайте отново или повикайте сервитьор.",
    loadError: "Не можем да проверим дали приемаме поръчки.",
    retry: "Опитай отново",
    allergens: "Алергени",
    allergensLead: "Ако имате алергии, моля, информирайте персонала.",
    choose: "Изберете",
    cancel: "Отказ",
    close: "Затвори",
    remove: "Премахни",
    less: "По-малко",
    more: "Още",
    categories: "Категории",
    orderedAt: "Поръчана в {time}",
  },
  en: {
    title: "Menu",
    restaurant: "RAYA Garden",
    table: "Table",
    tableN: "Table {n}",
    change: "change",
    chooseTable: "Which table are you at?",
    chooseTableLead: "The number is on the sign on your table.",
    justBrowsing: "Just browsing",
    add: "Add",
    added: "Added",
    soldOut: "Sold out",
    byWeight: "By weight · order from your waiter",
    per100: "per 100 g",
    itemsOne: "1 item",
    itemsMany: "{n} items",
    review: "Review order",
    yourOrder: "Your order",
    note: "Note",
    notePlaceholder: "optional, e.g. no onion",
    total: "Total",
    payment: "Payment is made to staff.",
    payOnline: "You pay by card on your phone — Apple Pay, Google Pay or card. The order goes to the staff as soon as the payment is through.",
    payButton: "Pay {total}",
    toPayment: "Going to payment…",
    payNow: "Pay",
    paid: "Paid",
    refunded: "Refunded",
    confirmingPayment: "Confirming your payment…",
    unpaidReturn: "The payment was not completed, so the order has not been sent. You can pay now or order again.",
    paymentUnavailable: "Payment cannot start right now. Please try again — the order will not be duplicated.",
    confirmTable: "I confirm I am at table {n}",
    send: "Send order",
    sending: "Sending…",
    emptyCart: "You have not added anything yet.",
    closed: "Online ordering is closed at the moment.",
    notYetToday: "We open for orders today at {time}.",
    notYetOn: "We open for orders on {date} at {time}.",
    paused: "Ordering is paused for a moment. Please ask a waiter.",
    browseStill: "You can still browse the menu.",
    sent: "Your order has been sent",
    sentLead: "The staff can see it. Show the code if asked.",
    code: "Code",
    status: {
      pending_payment: "Awaiting payment · not sent yet",
      expired: "Not paid · not sent",
      new: "Sent · waiting for confirmation",
      accepted: "Accepted · being prepared",
      served: "Served",
      cancelled: "Cancelled",
    },
    myOrders: "My orders",
    ordersShort: "Orders",
    orderMore: "Order more",
    changedTitle: "The menu has changed",
    changedLead: "Your order was not sent. Please check the changes and send it again.",
    removedLine: "{name} — no longer available, removed",
    soldOutLine: "{name} — sold out, removed",
    priceLine: "{name}: {old} → {now}",
    tableInvalid: "Table {n} is not taking orders. Please choose your table again.",
    rateLimited: "Too many orders in a short time. Please try again shortly or ask a waiter.",
    network: "No connection. Check your internet and try again — the order will not be sent twice.",
    error: "Something went wrong. Please try again or ask a waiter.",
    loadError: "We cannot check whether ordering is open.",
    retry: "Try again",
    allergens: "Allergens",
    allergensLead: "If you have allergies, please tell our staff.",
    choose: "Choose",
    cancel: "Cancel",
    close: "Close",
    remove: "Remove",
    less: "Less",
    more: "More",
    categories: "Categories",
    orderedAt: "Ordered at {time}",
  },
};
