// Fallback data used only when Sanity is unreachable. The CMS is the
// source of truth — edit content in Studio, not here.
// Prices are in EUR. The UI shows BGN as a secondary currency,
// computed at render time using the fixed peg 1 EUR = 1.95583 BGN.

// Self-hosted base for the few bundled fallback photos in public/img/.
// (The old WordPress media URLs died when this domain moved to the new
// site; the real content images all come from Sanity.)
export const IMG = "https://rayagarden.bg/img";

export const rooms = {
  bg: [
    {
      id: "standard-park",
      name: "Стандартна стая · парк гледка",
      price: 72,
      size: 22,
      sleeps: 2,
      view: "Парк „Света гора“",
      image: `${IMG}/hotel-all-2.png`,
      amenities: [
        "Двойно или две единични легла",
        "Безплатен Wi-Fi",
        "Климатик · геотермално отопление",
        "Сейф, минибар, телевизор",
        "Самостоятелна баня с душ",
        "Безплатни тоалетни принадлежности",
      ],
    },
    {
      id: "standard-city",
      name: "Стандартна стая · градска гледка",
      price: 82,
      size: 22,
      sleeps: 2,
      view: "Велико Търново",
      image: `${IMG}/hotel-all-3.png`,
      amenities: [
        "Двойно или две единични легла",
        "Панорамна гледка към града",
        "Безплатен Wi-Fi",
        "Климатик · геотермално отопление",
        "Минибар, телевизор, сейф",
        "Премиум тоалетни принадлежности",
      ],
    },
    {
      id: "deluxe",
      name: "Апартамент",
      price: 113,
      size: 28,
      sleeps: 4,
      sleepsLabel: "4 (2+2)",
      view: "Велико Търново · с балкон",
      image: `${IMG}/hotel-all-5.png`,
      amenities: [
        "Кинг сайз легло",
        "Собствен балкон с гледка",
        "Просторна баня с вана",
        "Кафе и чай зона (Nespresso)",
        "Халати и чехли",
        "Late check-out при възможност",
      ],
    },
    {
      id: "junior-suite",
      name: "Junior Suite",
      price: 164,
      size: 38,
      sleeps: 3,
      view: "Велико Търново · с дневна зона",
      image: `${IMG}/hotel-all-8.png`,
      amenities: [
        "Кинг сайз легло + диван",
        "Отделна дневна зона",
        "Премиум баня с вана и душ",
        "Бутилка вино при посрещане",
        "Безплатен ранен check-in / късен check-out",
        "Закуска до стаята при заявка",
      ],
    },
    {
      id: "luxury-suite",
      name: "Luxury Suite",
      price: 246,
      size: 52,
      sleeps: 4,
      view: "Панорамна · отделна спалня и хол",
      image: `${IMG}/hotel-all-11.png`,
      amenities: [
        "Отделна спалня и хол",
        "Кинг сайз легло + разтегателен диван",
        "Луксозна баня с джакузи",
        "Бутилка шампанско + плато при посрещане",
        "VIP трансфер по заявка",
        "Личен консиерж по време на престоя",
      ],
    },
  ],
  en: [
    {
      id: "standard-park",
      name: "Standard Room · park view",
      price: 72,
      size: 22,
      sleeps: 2,
      view: "Sveta Gora park",
      image: `${IMG}/hotel-all-2.png`,
      amenities: [
        "Double or twin beds",
        "Free Wi-Fi",
        "AC · geothermal heating",
        "Safe, minibar, TV",
        "Private bathroom with shower",
        "Complimentary toiletries",
      ],
    },
    {
      id: "standard-city",
      name: "Standard Room · city view",
      price: 82,
      size: 22,
      sleeps: 2,
      view: "Veliko Tarnovo",
      image: `${IMG}/hotel-all-3.png`,
      amenities: [
        "Double or twin beds",
        "Panoramic city view",
        "Free Wi-Fi",
        "AC · geothermal heating",
        "Minibar, TV, safe",
        "Premium toiletries",
      ],
    },
    {
      id: "deluxe",
      name: "Apartment",
      price: 113,
      size: 28,
      sleeps: 4,
      sleepsLabel: "4 (2+2)",
      view: "Veliko Tarnovo · with balcony",
      image: `${IMG}/hotel-all-5.png`,
      amenities: [
        "King-size bed",
        "Private balcony with a view",
        "Spacious bathroom with bathtub",
        "Nespresso coffee & tea station",
        "Robes and slippers",
        "Late check-out on request",
      ],
    },
    {
      id: "junior-suite",
      name: "Junior Suite",
      price: 164,
      size: 38,
      sleeps: 3,
      view: "Veliko Tarnovo · with living area",
      image: `${IMG}/hotel-all-8.png`,
      amenities: [
        "King-size bed + sofa",
        "Separate living area",
        "Premium bathroom with tub and shower",
        "Welcome bottle of wine",
        "Free early check-in / late check-out",
        "In-room breakfast on request",
      ],
    },
    {
      id: "luxury-suite",
      name: "Luxury Suite",
      price: 246,
      size: 52,
      sleeps: 4,
      view: "Panoramic · separate bedroom & lounge",
      image: `${IMG}/hotel-all-11.png`,
      amenities: [
        "Separate bedroom and lounge",
        "King-size bed + pull-out sofa",
        "Luxury bathroom with jacuzzi",
        "Welcome champagne and fruit platter",
        "VIP airport transfer on request",
        "Personal concierge during your stay",
      ],
    },
  ],
  ro: [
    {
      id: "standard-park",
      name: "Cameră Standard · vedere parc",
      price: 72,
      size: 22,
      sleeps: 2,
      view: "Parcul Sveta Gora",
      image: `${IMG}/hotel-all-2.png`,
      amenities: [
        "Pat dublu sau două paturi simple",
        "Wi-Fi gratuit",
        "AC · încălzire geotermală",
        "Seif, minibar, TV",
        "Baie privată cu duș",
        "Articole de toaletă incluse",
      ],
    },
    {
      id: "standard-city",
      name: "Cameră Standard · vedere oraș",
      price: 82,
      size: 22,
      sleeps: 2,
      view: "Veliko Tarnovo",
      image: `${IMG}/hotel-all-3.png`,
      amenities: [
        "Pat dublu sau două paturi simple",
        "Vedere panoramică asupra orașului",
        "Wi-Fi gratuit",
        "AC · încălzire geotermală",
        "Minibar, TV, seif",
        "Articole de toaletă premium",
      ],
    },
    {
      id: "deluxe",
      name: "Apartament",
      price: 113,
      size: 28,
      sleeps: 4,
      sleepsLabel: "4 (2+2)",
      view: "Veliko Tarnovo · cu balcon",
      image: `${IMG}/hotel-all-5.png`,
      amenities: [
        "Pat king-size",
        "Balcon privat cu vedere",
        "Baie spațioasă cu cadă",
        "Stație Nespresso pentru cafea și ceai",
        "Halate și papuci",
        "Check-out târziu la cerere",
      ],
    },
    {
      id: "junior-suite",
      name: "Junior Suite",
      price: 164,
      size: 38,
      sleeps: 3,
      view: "Veliko Tarnovo · cu zonă de zi",
      image: `${IMG}/hotel-all-8.png`,
      amenities: [
        "Pat king-size + canapea",
        "Zonă de zi separată",
        "Baie premium cu cadă și duș",
        "Sticlă de vin de bun venit",
        "Check-in devreme / check-out târziu gratuit",
        "Mic dejun în cameră la cerere",
      ],
    },
    {
      id: "luxury-suite",
      name: "Luxury Suite",
      price: 246,
      size: 52,
      sleeps: 4,
      view: "Panoramic · dormitor și living separate",
      image: `${IMG}/hotel-all-11.png`,
      amenities: [
        "Dormitor și living separate",
        "Pat king-size + canapea extensibilă",
        "Baie de lux cu jacuzzi",
        "Șampanie și platou cu fructe de bun venit",
        "Transfer VIP la aeroport la cerere",
        "Concierge personal pe durata sejurului",
      ],
    },
  ],
};

