// Fallback data used only when Sanity is unreachable. The CMS is the
// source of truth — edit content in Studio, not here.
// Prices are in EUR. The UI shows BGN as a secondary currency,
// computed at render time using the fixed peg 1 EUR = 1.95583 BGN.

export const IMG = "https://rayagarden.bg/wp-content/uploads/2022/01";

export const rooms = {
  bg: [
    {
      id: "standard-park",
      name: "Стандартна стая · парк гледка",
      price: 72,
      size: 22,
      sleeps: 2,
      view: "Парк „Света гора“",
      image: `${IMG}/hotel-all-2.png`,
      amenities: [
        "Двойно или две единични легла",
        "Безплатен Wi-Fi",
        "Климатик · геотермално отопление",
        "Сейф, минибар, телевизор",
        "Самостоятелна баня с душ",
        "Безплатни тоалетни принадлежности",
      ],
    },
    {
      id: "standard-city",
      name: "Стандартна стая · градска гледка",
      price: 82,
      size: 22,
      sleeps: 2,
      view: "Велико Търново",
      image: `${IMG}/hotel-all-3.png`,
      amenities: [
        "Двойно или две единични легла",
        "Панорамна гледка към града",
        "Безплатен Wi-Fi",
        "Климатик · геотермално отопление",
        "Минибар, телевизор, сейф",
        "Премиум тоалетни принадлежности",
      ],
    },
    {
      id: "deluxe",
      name: "Апартамент",
      price: 113,
      size: 28,
      sleeps: 2,
      view: "Велико Търново · с балкон",
      image: `${IMG}/hotel-all-5.png`,
      amenities: [
        "Кинг сайз легло",
        "Собствен балкон с гледка",
        "Просторна баня с вана",
        "Кафе и чай зона (Nespresso)",
        "Халати и чехли",
        "Late check-out при възможност",
      ],
    },
    {
      id: "junior-suite",
      name: "Junior Suite",
      price: 164,
      size: 38,
      sleeps: 3,
      view: "Велико Търново · с дневна зона",
      image: `${IMG}/hotel-all-8.png`,
      amenities: [
        "Кинг сайз легло + диван",
        "Отделна дневна зона",
        "Премиум баня с вана и душ",
        "Бутилка вино при посрещане",
        "Безплатен ранен check-in / късен check-out",
        "Закуска до стаята при заявка",
      ],
    },
    {
      id: "luxury-suite",
      name: "Luxury Suite",
      price: 246,
      size: 52,
      sleeps: 4,
      view: "Панорамна · отделна спалня и хол",
      image: `${IMG}/hotel-all-11.png`,
      amenities: [
        "Отделна спалня и хол",
        "Кинг сайз легло + разтегателен диван",
        "Луксозна баня с джакузи",
        "Бутилка шампанско + плато при посрещане",
        "VIP трансфер по заявка",
        "Личен консиерж по време на престоя",
      ],
    },
  ],
  en: [
    {
      id: "standard-park",
      name: "Standard Room · park view",
      price: 72,
      size: 22,
      sleeps: 2,
      view: "Sveta Gora park",
      image: `${IMG}/hotel-all-2.png`,
      amenities: [
        "Double or twin beds",
        "Free Wi-Fi",
        "AC · geothermal heating",
        "Safe, minibar, TV",
        "Private bathroom with shower",
        "Complimentary toiletries",
      ],
    },
    {
      id: "standard-city",
      name: "Standard Room · city view",
      price: 82,
      size: 22,
      sleeps: 2,
      view: "Veliko Tarnovo",
      image: `${IMG}/hotel-all-3.png`,
      amenities: [
        "Double or twin beds",
        "Panoramic city view",
        "Free Wi-Fi",
        "AC · geothermal heating",
        "Minibar, TV, safe",
        "Premium toiletries",
      ],
    },
    {
      id: "deluxe",
      name: "Apartment",
      price: 113,
      size: 28,
      sleeps: 2,
      view: "Veliko Tarnovo · with balcony",
      image: `${IMG}/hotel-all-5.png`,
      amenities: [
        "King-size bed",
        "Private balcony with a view",
        "Spacious bathroom with bathtub",
        "Nespresso coffee & tea station",
        "Robes and slippers",
        "Late check-out on request",
      ],
    },
    {
      id: "junior-suite",
      name: "Junior Suite",
      price: 164,
      size: 38,
      sleeps: 3,
      view: "Veliko Tarnovo · with living area",
      image: `${IMG}/hotel-all-8.png`,
      amenities: [
        "King-size bed + sofa",
        "Separate living area",
        "Premium bathroom with tub and shower",
        "Welcome bottle of wine",
        "Free early check-in / late check-out",
        "In-room breakfast on request",
      ],
    },
    {
      id: "luxury-suite",
      name: "Luxury Suite",
      price: 246,
      size: 52,
      sleeps: 4,
      view: "Panoramic · separate bedroom & lounge",
      image: `${IMG}/hotel-all-11.png`,
      amenities: [
        "Separate bedroom and lounge",
        "King-size bed + pull-out sofa",
        "Luxury bathroom with jacuzzi",
        "Welcome champagne and fruit platter",
        "VIP airport transfer on request",
        "Personal concierge during your stay",
      ],
    },
  ],
  ro: [
    {
      id: "standard-park",
      name: "Cameră Standard · vedere parc",
      price: 72,
      size: 22,
      sleeps: 2,
      view: "Parcul Sveta Gora",
      image: `${IMG}/hotel-all-2.png`,
      amenities: [
        "Pat dublu sau două paturi simple",
        "Wi-Fi gratuit",
        "AC · încălzire geotermală",
        "Seif, minibar, TV",
        "Baie privată cu duș",
        "Articole de toaletă incluse",
      ],
    },
    {
      id: "standard-city",
      name: "Cameră Standard · vedere oraș",
      price: 82,
      size: 22,
      sleeps: 2,
      view: "Veliko Tarnovo",
      image: `${IMG}/hotel-all-3.png`,
      amenities: [
        "Pat dublu sau două paturi simple",
        "Vedere panoramică asupra orașului",
        "Wi-Fi gratuit",
        "AC · încălzire geotermală",
        "Minibar, TV, seif",
        "Articole de toaletă premium",
      ],
    },
    {
      id: "deluxe",
      name: "Apartament",
      price: 113,
      size: 28,
      sleeps: 2,
      view: "Veliko Tarnovo · cu balcon",
      image: `${IMG}/hotel-all-5.png`,
      amenities: [
        "Pat king-size",
        "Balcon privat cu vedere",
        "Baie spațioasă cu cadă",
        "Stație Nespresso pentru cafea și ceai",
        "Halate și papuci",
        "Check-out târziu la cerere",
      ],
    },
    {
      id: "junior-suite",
      name: "Junior Suite",
      price: 164,
      size: 38,
      sleeps: 3,
      view: "Veliko Tarnovo · cu zonă de zi",
      image: `${IMG}/hotel-all-8.png`,
      amenities: [
        "Pat king-size + canapea",
        "Zonă de zi separată",
        "Baie premium cu cadă și duș",
        "Sticlă de vin de bun venit",
        "Check-in devreme / check-out târziu gratuit",
        "Mic dejun în cameră la cerere",
      ],
    },
    {
      id: "luxury-suite",
      name: "Luxury Suite",
      price: 246,
      size: 52,
      sleeps: 4,
      view: "Panoramic · dormitor și living separate",
      image: `${IMG}/hotel-all-11.png`,
      amenities: [
        "Dormitor și living separate",
        "Pat king-size + canapea extensibilă",
        "Baie de lux cu jacuzzi",
        "Șampanie și platou cu fructe de bun venit",
        "Transfer VIP la aeroport la cerere",
        "Concierge personal pe durata sejurului",
      ],
    },
  ],
};


export const eventsPackages = {
  bg: {
    weddings: [
      {
        tier: "Класически пакет",
        priceEur: 41,
        unit: "гост",
        capacity: "до 270 гости",
        includes: [
          "Меню от 5 предястия и 2 основни",
          "Безалкохолни напитки и вода",
          "Декорация на маси",
          "Сватбен координатор",
          "Безплатна стая за младоженците",
          "Озвучителна и осветителна система",
        ],
      },
      {
        tier: "Премиум пакет",
        priceEur: 77,
        unit: "гост",
        capacity: "до 200 гости",
        includes: [
          "Меню от 7 предястия, 3 основни, селекция десерти",
          "Селекция вина от Винарна Ялово",
          "Жива музика (квартет)",
          "Професионален фотограф (4 часа)",
          "Луксозен апартамент за младоженците",
          "Фойерверки за първия танц",
          "Безплатна стая за родителите",
        ],
      },
      {
        tier: "Сватбен ден извън сезон",
        priceEur: 31,
        unit: "гост",
        capacity: "до 150 гости",
        includes: [
          "Намалена цена ноември–март",
          "Същото качество и обслужване",
          "Възможност за зимна сватба сред природата",
          "Стая за младоженците с -50%",
        ],
      },
    ],
    corporate: [
      {
        tier: "Конференция · половин ден",
        priceEur: 24,
        unit: "участник",
        capacity: "до 80 души",
        includes: [
          "Зала с проектор и Wi-Fi",
          "Бутилирана вода и кафе/чай",
          "Една кафе пауза със сладко и солено",
          "Бележник и химикал",
        ],
      },
      {
        tier: "Целодневна конференция",
        priceEur: 34,
        unit: "участник",
        capacity: "до 80 души",
        includes: [
          "Зала с пълно техническо оборудване",
          "Две кафе паузи",
          "Бизнес обяд (3 блюда)",
          "Безплатен паркинг",
        ],
      },
      {
        tier: "Тиймбилдинг 2 дни",
        priceEur: 123,
        unit: "участник",
        capacity: "до 120 души",
        includes: [
          "1 нощувка в стандартна стая",
          "Закуска, обяд, вечеря",
          "Активности в парк „Света гора“",
          "Винена дегустация във Винарна Ялово",
          "Координатор за програмата",
        ],
      },
    ],
  },
  en: {
    weddings: [
      {
        tier: "Classic Package",
        priceEur: 41,
        unit: "guest",
        capacity: "up to 270 guests",
        includes: [
          "5 starters and 2 main courses",
          "Soft drinks and water",
          "Table decoration",
          "Wedding coordinator",
          "Free suite for the newlyweds",
          "Sound and lighting system",
        ],
      },
      {
        tier: "Premium Package",
        priceEur: 77,
        unit: "guest",
        capacity: "up to 200 guests",
        includes: [
          "7 starters, 3 mains, dessert selection",
          "Wine pairing from Yalovo Winery",
          "Live music (quartet)",
          "Professional photographer (4 hours)",
          "Luxury suite for the newlyweds",
          "Fireworks for the first dance",
          "Complimentary room for parents",
        ],
      },
      {
        tier: "Off-season Wedding",
        priceEur: 31,
        unit: "guest",
        capacity: "up to 150 guests",
        includes: [
          "Reduced rate November–March",
          "Same quality and service",
          "Winter wedding in nature",
          "Suite for newlyweds at -50%",
        ],
      },
    ],
    corporate: [
      {
        tier: "Half-day Conference",
        priceEur: 24,
        unit: "participant",
        capacity: "up to 80 people",
        includes: [
          "Hall with projector and Wi-Fi",
          "Bottled water and coffee/tea",
          "One coffee break (sweet & savoury)",
          "Notepad and pen",
        ],
      },
      {
        tier: "Full-day Conference",
        priceEur: 34,
        unit: "participant",
        capacity: "up to 80 people",
        includes: [
          "Hall with full AV setup",
          "Two coffee breaks",
          "Business lunch (3 courses)",
          "Free parking",
        ],
      },
      {
        tier: "2-day Team Building",
        priceEur: 123,
        unit: "participant",
        capacity: "up to 120 people",
        includes: [
          "1 night in standard room",
          "Breakfast, lunch, dinner",
          "Activities in Sveta Gora park",
          "Wine tasting at Yalovo Winery",
          "Program coordinator",
        ],
      },
    ],
  },
  ro: {
    weddings: [
      {
        tier: "Pachet Clasic",
        priceEur: 41,
        unit: "invitat",
        capacity: "până la 270 invitați",
        includes: [
          "5 aperitive și 2 feluri principale",
          "Băuturi nealcoolice și apă",
          "Decor de masă",
          "Coordonator de nuntă",
          "Apartament gratuit pentru miri",
          "Sistem de sunet și lumini",
        ],
      },
      {
        tier: "Pachet Premium",
        priceEur: 77,
        unit: "invitat",
        capacity: "până la 200 invitați",
        includes: [
          "7 aperitive, 3 feluri principale, selecție de deserturi",
          "Selecție de vinuri de la Crama Yalovo",
          "Muzică live (cvartet)",
          "Fotograf profesionist (4 ore)",
          "Apartament de lux pentru miri",
          "Artificii pentru primul dans",
          "Cameră gratuită pentru părinți",
        ],
      },
      {
        tier: "Nuntă extra-sezon",
        priceEur: 31,
        unit: "invitat",
        capacity: "până la 150 invitați",
        includes: [
          "Tarif redus noiembrie–martie",
          "Aceeași calitate și servicii",
          "Nuntă de iarnă în mijlocul naturii",
          "Apartament pentru miri la -50%",
        ],
      },
    ],
    corporate: [
      {
        tier: "Conferință de jumătate de zi",
        priceEur: 24,
        unit: "participant",
        capacity: "până la 80 persoane",
        includes: [
          "Sală cu proiector și Wi-Fi",
          "Apă îmbuteliată și cafea/ceai",
          "O pauză de cafea (dulce și sărat)",
          "Caiet și pix",
        ],
      },
      {
        tier: "Conferință de o zi",
        priceEur: 34,
        unit: "participant",
        capacity: "până la 80 persoane",
        includes: [
          "Sală cu echipament AV complet",
          "Două pauze de cafea",
          "Prânz business (3 feluri)",
          "Parcare gratuită",
        ],
      },
      {
        tier: "Teambuilding 2 zile",
        priceEur: 123,
        unit: "participant",
        capacity: "până la 120 persoane",
        includes: [
          "1 noapte în cameră standard",
          "Mic dejun, prânz, cină",
          "Activități în parcul Sveta Gora",
          "Degustare de vinuri la Crama Yalovo",
          "Coordonator de program",
        ],
      },
    ],
  },
};
